name: db
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    network_mode: "bridge"
    ports:
      - "1433:1433"
      - "1434:1434/udp"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    volumes:
      - "./entrypoint.sh:/entrypoint.sh"
      - "./backup:/var/opt/mssql/backup"
    entrypoint: "/entrypoint.sh"
  redis:
    image: redis
    container_name: redis
    network_mode: "bridge"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    tmpfs:
      - /data
    ports:
      - "6379:6379"